POE/POE/Controllers/StudyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;

namespace POE.Controllers
{
    public class StudyController : Controller
    {
        // this is used to read Settings and Connection Strings from AppSettings. json file
        private readonly IConfiguration configuration;

        public StudyController(IConfiguration config)
        {
            this.configuration = config;
        }
        

        public IActionResult AddModule()
        {
            //declaring a variable which will contain the connection to my database
            string connectionstring = configuration.GetConnectionString("DefaultConnection");

            SqlConnection con = new SqlConnection(connectionstring);
            con.Open();// opening the connection
            
            string moduleQuery = "SELECT MODULE_CODE FROM MODULES";
            SqlCommand cmd = new SqlCommand(moduleQuery, con);
            var modules = cmd.ExecuteReader();
            List<string> _moduleList = new List<string>();//declaring a list that will store the module codes from the database
            while (modules.Read())// creating a while loop that will loop through the module_code column from the database
            {
                _moduleList.Add(modules.GetValue(0).ToString());// getting the value of the code and adding the name to the list I declared to be displayed
            }
            ViewBag.data = _moduleList;//type of dictionary that stores the data internally to be displayed, this will store all the module codes from the database
            return View();
            
        }
        
        public IActionResult LogStudyHours()
        {
            try
            {
                //function.ConnectionString uses the ClassLibrary to get the method that was created in the Functions
                //class that stores the ConnectionString
                string connectionstring = configuration.GetConnectionString("DefaultConnection");

                SqlConnection con = new SqlConnection(connectionstring);
                con.Open();// opening the connection 
                string sqlquery = "SELECT * FROM dbo.SEMESTER_MODULE_DETAILS " +
                    "WHERE USER_ID = '" + this.result + "'"; //this would be used to get the information for the logged in student
                SqlCommand cmd = new SqlCommand(sqlquery, con);
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    LogStudyHours.inputModName.Items.Add(dr["MODULE_CODE"]);// this would be used to populate the form with the modules of that student and give them an option to choose
                }
                con.Close();// closing the connection
            }
            catch (Exception)
            {
                //this would be to display that message saying that theres an error that has occured
                TempData["msg"] = "<script>alert('An error has occured!');</script>";
            }
            return View();
        }
        public IActionResult ViewModules()
        {
            return View();
        }
    }
}

POE/POE/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using POE.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using PartOneLibrary;
namespace POE.Controllers
{
    public class UserController : Controller
    {
        //calling the Functions class from the custom class library
        Functions function = new Functions();
        // this is used to read Settings and Connection Strings from AppSettings. json file
        private readonly IConfiguration configuration;

        public UserController(IConfiguration config)
        {
            this.configuration = config;
        }
        public IActionResult MainPage()
        {
            return View();
        }

        public IActionResult Login()
        {
            //using try catch in case of errors that might occur when running the application
            try
            {
                //declaring a variable which will contain the connection to my database
                string connectionstring = configuration.GetConnectionString("DefaultConnection");

                SqlConnection con = new SqlConnection(connectionstring);
                con.Open();// openining the connection
                string add_data = "SELECT COUNT(USER_NAME) FROM dbo.USERS WHERE USER_NAME = @USER_NAME AND USER_PASSWORD = @USER_PASSWORD";
                SqlCommand cmd = new SqlCommand(add_data, con);
                cmd.Parameters.AddWithValue("@USER_NAME",Login.username.Text);// supposed to get the username the user input from the Login page
                string newPassword = function.HashPassword(Login.pass.Text);// supposed to get the password the user input from the Login page
                cmd.Parameters.AddWithValue("@USER_PASSWORD", newPassword);
                int Count = Convert.ToInt32(cmd.ExecuteScalar());
                con.Close();// closing the connection
                Login.pass.Text = "";
                if (Count > 0)
                {
                    con.Open();
                    string query = "SELECT USER_ID FROM dbo.USERS WHERE USER_NAME = '" + Login.username.Text.Text.Trim() + "'";// supposed to get the data from the database where the userName is equal to the username the user inserted in the login page
                    SqlCommand cmd2 = new SqlCommand(query, con);
                    Int32 result = (Int32)cmd2.ExecuteScalar();
                    con.Close();
                }
                else
                {
                    ///this would be to clear the form when incorrect information is added
                    username.Clear();
                    pass.Clear();
                    //this would be to display that message saying that the password or information is incorrect
                    TempData["msg"] = "<script>alert('Password or username is not correct');</script>";
                    //if password or username is incorrect and 
                    //doesnt match that from the DB it will show the user this message telling them that what they
                    //entered is wrong
                }
            }
            catch (Exception )
            {
               
            }
             return View();
        }
        
        //this method will check in the databse, what the last user ID was then populate the next userID for 
        //a new student that wants to sign up
        public IActionResult SignUp()
        {
            //declaring a variable which will contain the connection to my datase
            string connectionstring = configuration.GetConnectionString("DefaultConnection");

            SqlConnection con = new SqlConnection(connectionstring);
       
            int userId;
            string query = "SELECT USER_ID FROM dbo.USERS ORDER BY USER_ID DESC";
            con.Open();
            SqlCommand cmd = new SqlCommand(query, con);
            SqlDataReader dr = cmd.ExecuteReader();

            if (dr.Read())
            {
                int id = int.Parse(dr[0].ToString()) + 1;
                userId = id;
            }
            else if (Convert.IsDBNull(dr))
            {
                userId = 0000;
            }
            else
            {
                userId = 0001;
            }

            con.Close();
            //type of dictionary that stores the data internally to be displayed
            ViewData["UserId"] = userId.ToString();
            return View();
        }

        //public void SigningUp()
        //{
        //    string connectionstring = configuration.GetConnectionString("DefaultConnection");
        //    SqlConnection con = new SqlConnection(connectionstring);
        //    con.Open();
        //    string add_data = "INSERT INTO dbo.USERS VALUES( @USER_NAME, @USER_PASSWORD)";
        //    SqlCommand cmd = new SqlCommand(add_data, con);
        //    cmd.Parameters.AddWithValue("@USER_NAME", Username.text);
        //    //function.HashPassword executes the method that is in the class library for hashing a password
        //    cmd.Parameters.AddWithValue("@USER_PASSWORD", function.HashPassword(password.Password));
        //    cmd.ExecuteNonQuery();
        //    con.Close();
        //}

    }
        
    
}

POE/POE/Views/Shared/StudyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Study" asp-action="AddModule">Student Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Study" asp-action="AddModule">AddModule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Study" asp-action="LogStudyHours">LogStudyHours</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Study" asp-action="ViewModules">ViewModules</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDemoApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

POE/POE/Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="MainPage">Student Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MainPage">Main Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">SignUp</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDemoApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

POE/POE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Portal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="MainPage">MainPage</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignUp">SignUp Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Study" asp-action="AddModule">AddModule</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDemoApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>